<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="token.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SpotifyAPI.Web" Version="7.4.2" />
    <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.4.2" />
  </ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.Windows.SDK.NET.Ref" />
	</ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>